### ISSUE TITLE
Header issue in `avastel-ips-7d.txt`

### ISSUE THREAD

**Issue by Niek** [antoinevastel/avastel-bot-ips-lists#1]
The file [`avastel-ips-7d.txt`](https://raw.githubusercontent.com/antoinevastel/avastel-bot-ips-lists/master/avastel-ips-7d.txt) has a small issue: the header says `ip_address;num_days;autonomous_system` but the `num_days` column in not available in the rows.

**Comment by antoinevastel** [comment]
Thanks for your feedback. I will look at it and fix it soon :)

**Comment by antoinevastel** [comment]
It's solved now
