### ISSUE TITLE
Invalid IPv4 IPs in `avastel-ips-7d.txt`

### ISSUE THREAD

**Issue by Niek** [antoinevastel/avastel-bot-ips-lists#2]
There are 2 invalid IPv4 IPs in the file [`avastel-ips-7d.txt`](https://raw.githubusercontent.com/antoinevastel/avastel-bot-ips-lists/master/avastel-ips-7d.txt): both start with `::ffff:`.

**Comment by antoinevastel** [comment]
It's solved now
